In [ ]:
import numpy as np 
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

In [ ]:
dataset=pd.read_csv("pima-indians-diabetes.csv")

FileNotFoundError: ignored

In [ ]:
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [ ]:
type(dataset)

numpy.ndarray

In [ ]:
dataset.shape

(768, 9)

In [ ]:
dataset[0]

array([  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
        50.   ,   1.   ])

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
X=dataset[:,0:8]
Y=dataset[:,8]

In [ ]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [ ]:
Y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [ ]:
X.shape

(768, 8)

In [ ]:
model=Sequential()
model.add(Dense(12,input_dim=8,kernel_initializer='uniform',activation='relu'))
model.add(Dense(8,kernel_initializer='uniform',activation='relu'))
model.add(Dense(1,kernel_initializer='uniform',activation='sigmoid'))


In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 12)                108       
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 9         
Total params: 221
Trainable params: 221
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.fit(X,Y,epochs=500,batch_size=10)

Epoch 1/500
77/77 [==============================] - 1s 1ms/step - loss: 0.6842 - accuracy: 0.6385
Epoch 2/500
77/77 [==============================] - 0s 1ms/step - loss: 0.6463 - accuracy: 0.6746
Epoch 3/500
77/77 [==============================] - 0s 1ms/step - loss: 0.6479 - accuracy: 0.6556
Epoch 4/500
77/77 [==============================] - 0s 1ms/step - loss: 0.6376 - accuracy: 0.6717
Epoch 5/500
77/77 [==============================] - 0s 1ms/step - loss: 0.6350 - accuracy: 0.6705
Epoch 6/500
77/77 [==============================] - 0s 1ms/step - loss: 0.6321 - accuracy: 0.6662
Epoch 7/500
77/77 [==============================] - 0s 1ms/step - loss: 0.6034 - accuracy: 0.6857
Epoch 8/500
77/77 [==============================] - 0s 1ms/step - loss: 0.6259 - accuracy: 0.6493
Epoch 9/500
77/77 [==============================] - 0s 1ms/step - loss: 0.6135 - accuracy: 0.6718
Epoch 10/500
77/77 [==============================] - 0s 1ms/step - loss: 0.6177 - accuracy: 0.6746
Epoch 11/

In [ ]:
scores=model.evaluate(X,Y)

24/24 [==============================] - 0s 945us/step - loss: 0.4193 - accuracy: 0.7956


In [ ]:
print(model.metrics_names)

['loss', 'accuracy']


In [ ]:
scores

[0.4193135201931, 0.7955729365348816]